FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY target/banking-system-0.0.1-SNAPSHOT.jar banking-system-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/banking-system-0.0.1-SNAPSHOT.jar"]
